import assert from 'node:assert/strict';

export async function testDrag(page) {
  const saved = () => page.waitForFunction(() => document.querySelector('.app-shell').dataset.saveState === 'Saved');
  await saved();
  const before = (await (await page.request.get(new URL('/api/workspace',page.url()).href)).json()).map;
  const city = page.locator('[data-object-id="obj:city"]');
  const order = () => page.locator('.object-card').evaluateAll(nodes => nodes.sort((a,b) => parseFloat(a.style.translate)-parseFloat(b.style.translate)).map(node=>node.dataset.objectId));
  const originalOrder = await order();
  const originalIndex = originalOrder.indexOf('obj:city');
  const zoom = Number(await page.locator('.world').getAttribute('data-zoom'));
  const title = city.getByRole('button', {name:'Select City',exact:true});
  const bounds = await title.boundingBox();
  const origin = {x:bounds.x+15, y:bounds.y+8};
  await page.mouse.move(origin.x,origin.y);
  await page.mouse.down();
  await page.mouse.move(origin.x+2,origin.y+1);
  assert.equal(await page.locator('.column-drop-slot').count(),0,'Pointer noise must not initiate dragging');
  await page.mouse.move(origin.x+282*zoom,origin.y+24,{steps:12});
  await page.waitForTimeout(50);
  assert.equal(await city.getAttribute('data-dragging'),'true');
  const following = await title.boundingBox();
  assert.ok(Math.abs(following.x-bounds.x-282*zoom)<1,'Column tracks pointer exactly at canvas zoom');
  assert.ok(Math.abs(following.y-bounds.y-24)<1,'Vertical movement follows the pointer');
  assert.equal(await page.locator('.column-drop-slot').count(),1);
  await page.screenshot({path:'test-results/column-drag.png'});
  await page.mouse.up();
  await page.waitForTimeout(250);
  const reordered = await order();
  assert.equal(reordered.indexOf('obj:city'),originalIndex+1);
  const settled = await title.boundingBox();
  assert.ok(Math.abs(settled.y-bounds.y)<1,'Dropped column returns to the shared baseline');
  await saved();
  const workspace = await (await page.request.get(new URL('/api/workspace',page.url()).href)).json();
  assert.deepEqual(workspace.map,before,'Dragging changes visual layout only');
  await page.reload();
  await city.waitFor();
  assert.deepEqual(await order(),reordered,'Order persists across reload');

  const start = await title.boundingBox();
  await page.mouse.move(start.x+15,start.y+8);
  await page.mouse.down();
  await page.mouse.move(start.x+15-282*zoom,start.y+35,{steps:10});
  await page.keyboard.press('Escape');
  await page.mouse.up();
  await page.waitForTimeout(250);
  assert.deepEqual(await order(),reordered,'Escape restores the previous order');
  assert.equal(await page.locator('.column-drop-slot').count(),0);

  // Restore the fixture order before the independent focus tests.
  const restore = await title.boundingBox();
  await page.mouse.move(restore.x+15,restore.y+8);
  await page.mouse.down();
  await page.mouse.move(restore.x+15-282*zoom,restore.y+8,{steps:10});
  await page.mouse.up();
  await page.waitForTimeout(250);
  assert.deepEqual(await order(),originalOrder);
  await saved();
  const beforeScroll = await page.locator('.world').evaluate(el=>getComputedStyle(el).transform);
  const edgeStart = await title.boundingBox();
  await page.mouse.move(edgeStart.x+15,edgeStart.y+8);
  await page.mouse.down();
  await page.mouse.move(1430,edgeStart.y+8,{steps:12});
  await page.waitForTimeout(350);
  const afterScroll = await page.locator('.world').evaluate(el=>getComputedStyle(el).transform);
  assert.notEqual(afterScroll,beforeScroll,'Holding a drag at the edge pans the canvas');
  await page.keyboard.press('Escape');
  await page.mouse.up();
  await page.waitForTimeout(250);
  assert.deepEqual(await order(),originalOrder);
  assert.equal(await page.locator('.world').evaluate(el=>getComputedStyle(el).transform),beforeScroll,'Cancelling restores the viewport too');
  const cancelStart = await title.boundingBox();
  await page.mouse.move(cancelStart.x+15,cancelStart.y+8);
  await page.mouse.down();
  await page.mouse.move(cancelStart.x+150,cancelStart.y+30,{steps:8});
  await city.locator('.object-heading').dispatchEvent('pointercancel',{pointerId:2});
  assert.equal(await page.locator('.column-drop-slot').count(),1,'A secondary pointer cannot cancel the drag');
  await city.locator('.object-heading').dispatchEvent('pointercancel',{pointerId:1});
  await page.mouse.up();
  await page.waitForTimeout(250);
  assert.equal(await page.locator('.column-drop-slot').count(),0);
  assert.deepEqual(await order(),originalOrder,'Pointer cancellation restores order');
  await title.dblclick();
  await city.locator('input.object-title').waitFor({state:'visible'});
  await page.keyboard.press('Escape');
  await page.reload();
  await city.waitFor();
  await page.waitForTimeout(350);
  console.log('Drag passed: threshold, pointer tracking, reorder, aligned drop, cancellation, persistence, unchanged semantics.');
}
