import assert from 'node:assert/strict';

export async function testEditing(page) {
  await page.getByRole('button', {name: 'Fit all objects (F)', exact: true}).click();
  await page.waitForTimeout(350);
  const city = page.locator('[data-object-id="obj:city"]');
  const country = city.locator('[data-motion-id="obj:city/attr:country"]');
  const label = country.getByRole('button', {name: 'Select Country', exact: true});
  await label.click();
  assert.equal(await country.locator('input').count(), 0, 'A single click selects without editing');
  assert.equal(await label.getAttribute('aria-pressed'), 'true');
  assert.ok((await country.getAttribute('class')).includes('selected-item'));
  const zoom = await page.locator('.world').getAttribute('data-zoom');
  await label.dblclick();
  const input = country.getByRole('textbox', {name: 'Country', exact: true});
  await input.fill('Nation');
  await input.press('Enter');
  await country.getByRole('button', {name: 'Select Nation', exact: true}).waitFor();
  assert.equal(await page.locator('.world').getAttribute('data-zoom'), zoom, 'Editing a label never double-click zooms');
  await page.waitForFunction(() => document.querySelector('.app-shell').dataset.saveState === 'Saved');
  const workspace = await (await page.request.get(new URL('/api/workspace', page.url()).href)).json();
  assert.equal(workspace.map.objects.find(o => o.id === 'obj:city').attributes.find(a => a.id === 'obj:city/attr:country').name, 'Nation', 'Renaming persists while the identifier stays stable');
  const renamed = country.getByRole('button', {name: 'Select Nation', exact: true});
  await renamed.focus();
  await page.keyboard.press('F2');
  await country.getByRole('textbox').fill('Country');
  await country.getByRole('textbox').press('Enter');
  const action = city.locator('[data-section="actions"] .mini-card').first();
  await action.getByRole('button', {name: 'Select Edit', exact: true}).click();
  assert.equal(await action.locator('input').count(), 0);
  assert.equal(await country.getByRole('button', {name: 'Select Country', exact: true}).getAttribute('aria-pressed'), 'false', 'Selecting another card replaces the previous selection');
  await action.getByRole('button', {name: 'Select Edit', exact: true}).dblclick();
  await action.getByRole('textbox').fill('Discard this');
  await action.getByRole('textbox').press('Escape');
  await action.getByRole('button', {name: 'Select Edit', exact: true}).waitFor();
  const owner = page.locator('[data-motion-id="obj:collection/rel:owner"]');
  const ownerLabel = owner.getByRole('button', {name: 'Select Owned by', exact: true});
  await ownerLabel.click();
  assert.equal(await ownerLabel.getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('.object-card.focused').count(), 0, 'Selecting a relationship does not navigate to its target');
  assert.equal(await owner.locator('.relationship-target').textContent(), 'Person');
  await ownerLabel.dblclick();
  await owner.getByRole('textbox', {name: 'Owned by', exact: true}).fill('Steward');
  await owner.getByRole('textbox', {name: 'Owned by', exact: true}).press('Enter');
  await owner.getByRole('button', {name: 'Select Steward', exact: true}).focus();
  await page.keyboard.press('F2');
  await owner.getByRole('textbox', {name: 'Steward', exact: true}).fill('Owned by');
  await owner.getByRole('textbox', {name: 'Steward', exact: true}).press('Enter');
  await owner.getByRole('button', {name: 'Go to Person', exact: true}).click();
  assert.ok((await page.locator('[data-object-id="obj:person"]').getAttribute('class')).includes('focused'), 'The link control follows the target');
  await page.getByRole('button', {name: 'Clear selection', exact: true}).click();
  assert.equal(await page.locator('.selected-item').count(), 0);
  console.log('Editing passed: single-click selection, double-click editing, keyboard rename, cancellation, stable IDs and persistence.');
}
